import type { Project, ProjectSummary, Scene } from './types';

const sampleScenes: Scene[] = [
  {
    id: 'sample-scene-01',
    sceneNumber: 1,
    heading: '内景．夜间控制室—深夜',
    location: '夜间控制室',
    timeOfDay: '深夜',
    summary: '顾言在例行巡检中听见每隔十七秒出现一次的求救广播。',
    action: '所有监视器同时跳过一帧。顾言停下笔，把声音推子拉到底。一阵不属于线路系统的呼吸声从音箱里传来。红色波形在屏幕上重复，间隔十七秒。',
    dialogue: [
      { character: '顾言', text: '线路里没有人。' },
      { character: '罗队', parenthetical: '耳机中', text: '那就别回答。把它当噪声。' },
      { character: '顾言', text: '噪声不会准时回来。' },
    ],
    estimatedSeconds: 70,
  },
  {
    id: 'sample-scene-02',
    sceneNumber: 2,
    heading: '内景．废弃站台—深夜',
    location: '废弃站台',
    timeOfDay: '深夜',
    summary: '顾言循声来到封闭站台，遇见拿着旧录音机的苏弥。',
    action: '废弃站台的灯依次亮起，像有人正从隧道深处走来。苏弥站在黄线外，手里那台旧录音机仍在转动，却没有插电。',
    dialogue: [
      { character: '苏弥', text: '你晚了十七秒。' },
      { character: '顾言', text: '这里不该有人。' },
      { character: '苏弥', text: '这句话，你们七年前也说过。' },
    ],
    estimatedSeconds: 65,
  },
  {
    id: 'sample-scene-03',
    sceneNumber: 3,
    heading: '内景．废弃站台—连续',
    location: '废弃站台',
    timeOfDay: '连续',
    summary: '罗队封锁出口，顾言被迫在命令与陌生人的证据之间选择。',
    action: '卷帘门猛地落下。绿色出口灯熄灭，只剩紧急电话闪烁。顾言看向摄像头，又看向苏弥递来的磁带，没有接。',
    dialogue: [
      { character: '罗队', parenthetical: '广播中', text: '顾言，把乘客留在原地。' },
      { character: '苏弥', text: '他知道我的名字，却只叫我乘客。' },
      { character: '顾言', text: '你到底要我修什么？' },
      { character: '苏弥', text: '不是修。是让它响完。' },
    ],
    estimatedSeconds: 75,
  },
  {
    id: 'sample-scene-04',
    sceneNumber: 4,
    heading: '内景．017 号检修隧道—深夜',
    location: '检修隧道',
    timeOfDay: '深夜',
    summary: '两人进入被地图删除的隧道，顾言发现自己曾参与掩盖事故。',
    action: '两束头灯切开黑暗。墙上的旧编号被新漆覆盖，顾言用手套擦开“017”。风从本该封死的岔道涌来，带着广播测试音。',
    dialogue: [
      { character: '顾言', text: '017 在图纸上已经不存在。' },
      { character: '苏弥', text: '图纸很擅长忘记。墙不擅长。' },
      { character: '顾言', parenthetical: '看见编号', text: '这份封存报告……是我签的。' },
    ],
    estimatedSeconds: 80,
  },
  {
    id: 'sample-scene-05',
    sceneNumber: 5,
    heading: '内景．隧道设备间—黎明前',
    location: '检修隧道',
    timeOfDay: '黎明前',
    summary: '真相将同时毁掉顾言的职业，苏弥把最后决定交还给他。',
    action: '设备柜里藏着一台仍在运行的备份机。屏幕显示顾言多年前的电子签名。苏弥按下播放键，一群人的声音挤进狭小房间。',
    dialogue: [
      { character: '苏弥', text: '播出去，你会和他们一起被记住。' },
      { character: '顾言', text: '不播呢？' },
      { character: '苏弥', text: '你已经试过七年了。' },
      { character: '罗队', parenthetical: '耳机中', text: '顾先生，请你最后一次按流程处理。' },
    ],
    estimatedSeconds: 85,
  },
  {
    id: 'sample-scene-06',
    sceneNumber: 6,
    heading: '内景．夜间控制室—黎明',
    location: '夜间控制室',
    timeOfDay: '黎明',
    summary: '顾言放弃安全退路，让被静音七年的声音进入全城广播。',
    action: '控制室外，天色把玻璃染成灰蓝。顾言将旧线路接入公共广播。所有警报同时亮起，他没有静音。城市停顿了一秒，然后听见了那段声音。',
    dialogue: [
      { character: '顾言', text: '流程编号，零一七。故障原因：人为静音。' },
      { character: '罗队', text: '切断它。' },
      { character: '顾言', parenthetical: '推起总控', text: '正在恢复。' },
    ],
    estimatedSeconds: 75,
  },
];

const screenplay = sampleScenes
  .map((scene) => {
    const dialogue = scene.dialogue
      .map((line) => `${line.character}\n${line.parenthetical ? `（${line.parenthetical}）\n` : ''}${line.text}`)
      .join('\n\n');
    return `${scene.heading}\n\n${scene.action}\n\n${dialogue}`;
  })
  .join('\n\n===\n\n');

export const sampleProject: Project = {
  id: 'sample',
  mode: 'ORIGINAL',
  title: '零点十七分',
  logline: '一名失眠的地铁维修工，在末班车后收到一段来自七年前事故现场的求救广播。',
  genre: '悬疑科幻',
  tone: '克制、潮湿，结尾带有希望',
  language: 'zh-CN',
  targetMinutes: 8,
  status: 'READY',
  currentStage: 'COMPLETE',
  expiresAt: null,
  premise: '当一段被城市删除的求救广播重新响起，曾经签字沉默的维修工必须在天亮前决定：继续维护秩序，还是让所有人听见真相。',
  synopsis: '地铁维修工顾言在夜班中捕捉到每隔十七秒出现一次的异常广播，并在封闭站台遇见携带旧录音机的苏弥。她声称广播来自七年前一场被掩盖的事故。主管罗队要求顾言删除记录并交出苏弥，两人只得进入已从图纸上消失的 017 号隧道。顾言在那里发现，自己当年签署的封存报告正是沉默得以延续的最后一环。天亮前，他必须付出职业和名誉的代价，把那段声音重新接入城市。',
  theme: '真正需要修复的，从来不是故障，而是我们选择忽略的裂缝。',
  characters: [
    {
      id: 'sample-character-01',
      name: '顾言',
      role: '主角 / 地铁维修工',
      age: '29',
      description: '习惯把情绪藏进工作流程的技术员，观察力强，却害怕承担选择的后果。',
      goal: '在天亮前解决异常并保住自己的工作。',
      conflict: '越依赖规则，越无法处理眼前这个没有标准答案的人。',
      arc: '从修补故障的旁观者，变成愿意为真相承担代价的行动者。',
      voice: '短句、精确、回避感受；紧张时会重复技术术语。',
    },
    {
      id: 'sample-character-02',
      name: '苏弥',
      role: '催化者 / 事故遗属',
      age: '24',
      description: '带着旧录音机的陌生乘客，敏锐、冷静，像是早已排练过这次相遇。',
      goal: '让一段被掩盖的声音在城市醒来前重新出现。',
      conflict: '她需要顾言帮助，却无法完全信任一个曾经选择沉默的人。',
      arc: '从把顾言当作工具，到允许他共同决定真相如何被看见。',
      voice: '用具体意象代替解释，语气平静，关键时刻直呼对方全名。',
    },
    {
      id: 'sample-character-03',
      name: '罗队',
      role: '对抗力量 / 夜间主管',
      age: '45',
      description: '负责夜间调度的主管，相信秩序比个体真相更重要。',
      goal: '在早高峰前封锁异常，避免系统性恐慌。',
      conflict: '他保护城市的方式，正是让旧错误继续存在的原因。',
      arc: '从掌控一切，到第一次被迫听见自己下令删除的声音。',
      voice: '命令式，几乎不用形容词；愤怒时反而变得礼貌。',
    },
  ],
  relationships: [
    {
      id: 'sample-relationship-01',
      sourceId: 'sample-character-01',
      targetId: 'sample-character-02',
      type: '被迫同盟',
      description: '苏弥需要顾言打开旧线路，顾言则需要她手中的录音理解自己曾参与掩盖的真相。互不信任让合作始终带着倒计时。',
      strength: 5,
      directed: false,
    },
    {
      id: 'sample-relationship-02',
      sourceId: 'sample-character-03',
      targetId: 'sample-character-01',
      type: '命令与控制',
      description: '罗队以工作流程和职业前途控制顾言，顾言的最终选择把这段上下级关系变成公开对抗。',
      strength: 4,
      directed: true,
    },
    {
      id: 'sample-relationship-03',
      sourceId: 'sample-character-02',
      targetId: 'sample-character-03',
      type: '追责',
      description: '苏弥要罗队代表的系统听见被删除的声音；罗队则把她视为必须在早高峰前封锁的风险。',
      strength: 4,
      directed: true,
    },
  ],
  locations: [
    {
      id: 'sample-location-01',
      name: '废弃站台',
      description: '被新线路绕开的旧站台，墙砖潮湿，广告牌停在很多年前。',
      atmosphere: '空旷、回声清晰，像一段不肯结束的记忆。',
      recurringElements: '闪烁的绿灯、积水倒影、远处规律的金属敲击声。',
    },
    {
      id: 'sample-location-02',
      name: '夜间控制室',
      description: '布满监视器和线路图的狭长房间，所有屏幕都比人脸更亮。',
      atmosphere: '高度可控，却始终有一块画面无法解释。',
      recurringElements: '红色倒计时、纸杯、被静音的警报。',
    },
    {
      id: 'sample-location-03',
      name: '检修隧道',
      description: '仅容两人并行的隧道，电缆像血管一样沿墙延伸。',
      atmosphere: '逼仄、危险，每一步都在接近城市不愿承认的内部。',
      recurringElements: '头灯光束、风压、旧编号 017。',
    },
  ],
  beats: [
    { id: 'sample-beat-01', act: 1, sequence: 1, title: '错误的回声', summary: '顾言值夜时发现一段来自封闭线路的异常求救广播。', emotionalShift: '从麻木到警觉' },
    { id: 'sample-beat-02', act: 1, sequence: 2, title: '不在名单上的乘客', summary: '苏弥从封闭区域出现，拿出一段只能在旧线路播放的录音。', emotionalShift: '从警觉到怀疑' },
    { id: 'sample-beat-03', act: 2, sequence: 3, title: '第一次封锁', summary: '罗队远程关闭出口，要求顾言交出乘客并删除记录。', emotionalShift: '从怀疑到被迫结盟' },
    { id: 'sample-beat-04', act: 2, sequence: 4, title: '017 号隧道', summary: '顾言发现异常与自己多年前签署的封存报告有关。', emotionalShift: '从自保到羞愧' },
    { id: 'sample-beat-05', act: 2, sequence: 5, title: '沉默的价格', summary: '苏弥承认公开录音也会让顾言失去工作与名誉。', emotionalShift: '从结盟到决裂' },
    { id: 'sample-beat-06', act: 3, sequence: 6, title: '全城广播', summary: '顾言放弃安全退路，将录音接入早高峰广播。', emotionalShift: '从逃避到承担' },
  ],
  scenes: sampleScenes,
  draft: null,
  scriptText: `Title: 零点十七分\nCredit: AI 辅助创作示例\nDraft date: 2026-08-08\n\n${screenplay}\n\n> 黑场。城市恢复了呼吸。`,
  createdAt: '2026-08-08T00:00:00.000Z',
  updatedAt: '2026-08-08T00:00:00.000Z',
};

export const sampleSummary: ProjectSummary = {
  id: sampleProject.id,
  title: sampleProject.title,
  logline: sampleProject.logline,
  genre: sampleProject.genre,
  tone: sampleProject.tone,
  targetMinutes: sampleProject.targetMinutes,
  status: sampleProject.status,
  currentStage: sampleProject.currentStage,
  expiresAt: sampleProject.expiresAt,
  createdAt: sampleProject.createdAt,
  updatedAt: sampleProject.updatedAt,
  _count: { scenes: sampleProject.scenes.length, characters: sampleProject.characters.length },
};
